name: brick_tests
description: Tests for Mason bricks in the Flutter App Template
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  mason: ^0.1.0-dev.60
  path: ^1.9.0
  
dev_dependencies:
  test: ^1.26.2
  lints: ^5.0.0