name: Brick Integration Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'all'
        type: choice
        options:
          - 'all'
          - 'unit'
          - 'api_client'
          - 'repository'
          - 'simple_bloc'
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'bricks/**'
      - 'tool/brick_tests/**'
      - '.github/workflows/brick-integration-tests.yml'

jobs:
  test-bricks:
    name: Test Bricks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: flutter-actions/setup-flutter@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install tools
        run: |
          dart pub global activate mason_cli
          dart pub global activate melos

      - name: Initialize project
        run: |
          flutter pub get
          melos bootstrap
          mason get

      - name: Install brick test dependencies
        run: |
          cd tool/brick_tests
          dart pub get

      - name: Validate brick structure
        run: |
          echo "=== Validating Brick Structure ==="
          dart run tool/brick_tests/validate_bricks.dart

      - name: Run brick tests
        run: |
          echo "=== Running Brick Tests ==="
          cd tool/brick_tests

          case "${{ inputs.test_type }}" in
            "all")
              echo "Running all brick tests..."
              dart run all_bricks_test.dart
              ;;
            "unit")
              echo "Running unit tests..."
              dart run api_client_test.dart
              dart run repository_test.dart
              dart run simple_bloc_test.dart
              ;;
            "api_client")
              echo "Running API client brick tests..."
              dart run api_client_test.dart
              ;;
            "repository")
              echo "Running repository brick tests..."
              dart run repository_test.dart
              ;;
            "simple_bloc")
              echo "Running simple BLoC brick tests..."
              dart run simple_bloc_test.dart
              ;;
            *)
              echo "Running all brick tests..."
              dart run all_bricks_test.dart
              ;;
          esac

      - name: Test brick generation
        run: |
          echo "=== Testing Brick Generation ==="
          TEMP_DIR=$(mktemp -d)

          if mason make api_client -o "$TEMP_DIR/test_api_client" --package_name=test_api_client; then
            echo "✅ API Client brick generation successful"
            cd "$TEMP_DIR/test_api_client"
            if dart pub get && dart analyze; then
              echo "✅ Generated code analysis passed"
            fi
            cd -
          fi

          rm -rf "$TEMP_DIR"
          echo "✅ Brick integration testing completed!"